# Generated by Django 5.0.6 on 2026-05-31 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('queja', 'Queja'), ('sugerencia', 'Sugerencia')], default='queja', max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('resuelta', 'Resuelta'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('anonima', models.BooleanField(default=False, verbose_name='Anónima')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='quejas/', verbose_name='Imagen')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quejas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quejas', to='quejas.departamento', verbose_name='Departamento')),
                ('votos', models.ManyToManyField(blank=True, related_name='quejas_votadas', to=settings.AUTH_USER_MODEL, verbose_name='Votos')),
            ],
            options={
                'verbose_name': 'Queja',
                'verbose_name_plural': 'Quejas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
